version: '3.8'

services:
  cacheDB:
    image: redis:latest
    ports:
    - "6379:6379"
    networks:
    - exo_network

  db:
    image: docker.io/postgres:latest
    environment:
      POSTGRES_DB: <your-database-name>
      POSTGRES_USER: <your-username>
      POSTGRES_PASSWORD: <your-password>
    ports:
    - "5432:5432"
    volumes:
    - ./postgresql-data:/var/lib/postgresql/data
    networks:
    - zen_network

  api:
    build:
      context: ./backend
      podmanfile: Podmanfile
    ports:
    - "8080:8080"
    depends_on:
    - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
    - ./backend:/app
    networks:
    - zen_network

  ui:
    build:
      context: ./frontend
      podmanfile: Podmanfile
    ports:
    - "3000:3000"
    depends_on:
    - api
    environment:
      REACT_APP_API_URL: "http://localhost:8080/api"
    volumes:
    - ./frontend:/app
    networks:
    - zen_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus:/etc/prometheus
    ports:
    - "9090:9090"
    networks:
    - zen_network

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
    - "3001:3000"
    networks:
    - zen_network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
    - "8025:8025"
    networks:
    - zen_network

networks:
  zen_network:
    driver: bridge
