# ===============================
# = DATA SOURCE
# ===============================
# Set configurations for the database connection

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  # ===============================
  # = JPA / HIBERNATE
  # ===============================

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # ===============================
  # = Keycloak
  # ===============================

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:28080/auth/realms/exocompanion

# ===============================
# = SpringDocs
# ===============================

springdoc:
  show-actuator: true